minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@tanstack/table-core@9.0.0'
  - '@tanstack/vue-table@9.0.0'
shellEmulator: true

trustPolicy: no-downgrade
autoInstallPeers: false
allowBuilds:
  maplibre-gl: true
  simple-git-hooks: true
  vue-demi: true
