services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user_id: 1000
        group_id: 1000
    depends_on:
      - database
    environment:
      PHP_OPCACHE_ENABLE: "1"
      AUTORUN_ENABLED: "true" # 👈 Remove this line if you don't want Laravel Automations
      HEALTHCHECK_PATH: "/up" # Use Laravel's built-in health route
      SSL_MODE: "full"
      LOG_OUTPUT_LEVEL: debug
    networks:
      - traefik_public
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "./storage:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"
      - "storage_svg:/var/www/html/storage/app/svg"
      - "./.env:/var/www/html/.env"
    deploy:
      replicas: 3
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 5s
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        # Enable Traefik
        - "traefik.enable=true"

        # HTTPS Router
        - "traefik.http.routers.php.rule=Host(`mimovel.com`) || Host(`www.mimovel.com`) || Host(`m.mimovel.com`) || Host(`web.mimovel.com`)"
        - "traefik.http.routers.php.entrypoints=websecure"
        - "traefik.http.routers.php.tls=true"
        - "traefik.http.routers.php.tls.certresolver=le"
        #- "traefik.http.services.php.loadbalancer.server.scheme=https"
        - "traefik.http.services.php.loadbalancer.server.scheme=http"


        # URL replacement middleware
        - "traefik.http.middlewares.https-replace.replacepathregex.regex=http://([^/]+)"
        - "traefik.http.middlewares.https-replace.replacepathregex.replacement=https://$$1"
        # Headers middleware
        - "traefik.http.middlewares.php-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
        # Chain middlewares
        - "traefik.http.routers.php.middlewares=php-headers,https-replace"
        # Service port (THIS IS WHAT WAS MISSING!)
        - "traefik.http.services.php.loadbalancer.server.port=8080"

        # Optional: HTTP to HTTPS redirect
        - "traefik.http.routers.php-http.rule=Host(`mimovel.com`) || Host(`www.mimovel.com`) || Host(`m.mimovel.com`) || Host(`web.mimovel.com`)"
        - "traefik.http.routers.php-http.entrypoints=web"
        - "traefik.http.routers.php-http.middlewares=php-https-redirect"
        - "traefik.http.middlewares.php-https-redirect.redirectscheme.scheme=https"
  workers:
    image: ghcr.io/inkomomutane/mimovel:latest
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    depends_on:
      - php
    stop_signal: SIGTERM
    networks:
      - traefik_public
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "./backup:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"
      - "storage_svg:/var/www/html/storage/app/svg"
      - "./.env:/var/www/html/.env"
    deploy:
      replicas: 2
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 5s
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=false"
  database:
    image: mysql:8.0
    secrets:
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: mimovel
      MYSQL_USER: mimovel_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - traefik_public
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 5s
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
volumes:
  storage_private:
  storage_sessions:
  storage_logs:
  storage_svg:
  db_data:
networks:
  traefik_public:
    external: true
secrets:
  db_password:
    external: true
