/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const API_BASE_URL: typeof import('../constants/app-config').API_BASE_URL
  const API_TIMEOUT: typeof import('../constants/app-config').API_TIMEOUT
  const CONTENT_LAYOUTS: typeof import('../constants/themes').CONTENT_LAYOUTS
  const DEFAULT_PAGE_SIZE: typeof import('../constants/app').DEFAULT_PAGE_SIZE
  const EffectScope: typeof import('vue').EffectScope
  const HOME_PATH: typeof import('../constants/app').HOME_PATH
  const LOGIN_PATH: typeof import('../constants/app').LOGIN_PATH
  const PAGE_SIZES: typeof import('../constants/app').PAGE_SIZES
  const RADIUS: typeof import('../constants/themes').RADIUS
  const THEMES: typeof import('../constants/themes').THEMES
  const THEME_PRIMARY_COLORS: typeof import('../constants/themes').THEME_PRIMARY_COLORS
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const definePage: typeof import('vue-router/experimental').definePage
  const effectScope: typeof import('vue').effectScope
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const logout: typeof import('../composables/use-auth')['logout']
  const markRaw: typeof import('vue').markRaw
  const navData: typeof import('../constants/sidebar-data').navData
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const otherPages: typeof import('../constants/sidebar-data').otherPages
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const resolveSystemConfigValue: typeof import('../composables/use-system-config-query').resolveSystemConfigValue
  const settingsNavItems: typeof import('../constants/sidebar-data').settingsNavItems
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useAuth: typeof import('../composables/use-auth').useAuth
  const useAuthStore: typeof import('../stores/auth').useAuthStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router')['useLink']
  const useModal: typeof import('../composables/use-modal').useModal
  const useModel: typeof import('vue').useModel
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSidebarConfigStore: typeof import('../stores/sidebar-config').useSidebarConfigStore
  const useSidebarNavigation: typeof import('../composables/use-sidebar-navigation').useSidebarNavigation
  const useSlots: typeof import('vue').useSlots
  const useSystemConfig: typeof import('../composables/use-system-config').useSystemConfig
  const useSystemConfigQuery: typeof import('../composables/use-system-config-query').useSystemConfigQuery
  const useSystemTheme: typeof import('../composables/use-system-theme').useSystemTheme
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useThemeConfig: typeof import('../composables/use-theme-config')['useThemeConfig']
  const useThemeStore: typeof import('../stores/theme').useThemeStore
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { Theme, Radius, ContentLayout } from '../constants/themes'
  import('../constants/themes')
  // @ts-ignore
  export type { NavigationMode } from '../stores/sidebar-config'
  import('../stores/sidebar-config')
}
