/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/ai-talk/': RouteRecordInfo<
      '/ai-talk/',
      '/ai-talk',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/apps/': RouteRecordInfo<
      '/apps/',
      '/apps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/'
      | '/auth/forgot-password'
      | '/auth/otp'
      | '/auth/sign-in'
      | '/auth/sign-in-2'
      | '/auth/sign-up'
    >,
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/forgot-password': RouteRecordInfo<
      '/auth/forgot-password',
      '/auth/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/otp': RouteRecordInfo<
      '/auth/otp',
      '/auth/otp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-in': RouteRecordInfo<
      '/auth/sign-in',
      '/auth/sign-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-in-2': RouteRecordInfo<
      '/auth/sign-in-2',
      '/auth/sign-in-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-up': RouteRecordInfo<
      '/auth/sign-up',
      '/auth/sign-up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/billing/': RouteRecordInfo<
      '/billing/',
      '/billing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors': RouteRecordInfo<
      '/errors',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | '/errors/'
      | '/errors/[code]'
    >,
    '/errors/': RouteRecordInfo<
      '/errors/',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/[code]': RouteRecordInfo<
      '/errors/[code]',
      '/errors/:code',
      { code: ParamValue<true> },
      { code: ParamValue<false> },
      | never
    >,
    '/help-center': RouteRecordInfo<
      '/help-center',
      '/help-center',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/marketing/': RouteRecordInfo<
      '/marketing/',
      '/marketing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/marketing/hello': RouteRecordInfo<
      '/marketing/hello',
      '/marketing/hello',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/prop-components/': RouteRecordInfo<
      '/prop-components/',
      '/prop-components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account': RouteRecordInfo<
      '/settings/account',
      '/settings/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/appearance': RouteRecordInfo<
      '/settings/appearance',
      '/settings/appearance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/display': RouteRecordInfo<
      '/settings/display',
      '/settings/display',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/notifications': RouteRecordInfo<
      '/settings/notifications',
      '/settings/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tasks/': RouteRecordInfo<
      '/tasks/',
      '/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/': RouteRecordInfo<
      '/users/',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/ai-talk/index.vue': {
      routes:
        | '/ai-talk/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/apps/index.vue': {
      routes:
        | '/apps/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/'
        | '/auth/forgot-password'
        | '/auth/otp'
        | '/auth/sign-in'
        | '/auth/sign-in-2'
        | '/auth/sign-up'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/forgot-password.vue': {
      routes:
        | '/auth/forgot-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/otp.vue': {
      routes:
        | '/auth/otp'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/sign-in.vue': {
      routes:
        | '/auth/sign-in'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/sign-in-2.vue': {
      routes:
        | '/auth/sign-in-2'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/sign-up.vue': {
      routes:
        | '/auth/sign-up'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/billing/index.vue': {
      routes:
        | '/billing/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors.vue': {
      routes:
        | '/errors'
        | '/errors/'
        | '/errors/[code]'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/errors/index.vue': {
      routes:
        | '/errors/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors/[code].vue': {
      routes:
        | '/errors/[code]'
      views:
        | never
      pathParamNames:
        | 'code'
    }
    'src/pages/help-center.vue': {
      routes:
        | '/help-center'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/marketing/index.vue': {
      routes:
        | '/marketing/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/marketing/hello.vue': {
      routes:
        | '/marketing/hello'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/prop-components/index.vue': {
      routes:
        | '/prop-components/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/account.vue': {
      routes:
        | '/settings/account'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/appearance.vue': {
      routes:
        | '/settings/appearance'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/display.vue': {
      routes:
        | '/settings/display'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/notifications.vue': {
      routes:
        | '/settings/notifications'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tasks/index.vue': {
      routes:
        | '/tasks/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/users/index.vue': {
      routes:
        | '/users/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
