name: 🚀 Build 🔥🔥🔥 🦅
on:
  push:
    branches:
    - main
env:
  FIRST_NAME: Mimovel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install dependeces via composer
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd mimovel
            ${{ secrets.FUN_GIT_PULL }}
            php composer.phar install --optimize-autoloader --no-dev
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          host: ${{ secrets.SSH_SERVER }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          #pass: ${{ secrets.SSH_PASS_KEY }}
          args: "-tt -vvv"
