name: Install compoer dependeces
on:
  push:
    branches:
    - main

env:
  FIRST_NAME: Mimovel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install dependeces via composer 
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd mimovel
            git config user.name github-actions
            git config user.email github-actions@github.com
            git fetch
            inkommutane
            git pull
            php composer.phar install
            exit 1
          host: ${{ secrets.SSH_SERVER }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          pass: ${{ secrets.SSH_PASS_KEY }}
          args: "-tt"
