name: Test ssh action
on:
  push:
    branches:
    - actions
env:
  FIRST_NAME: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run:  ${{ secrets.SSH_PRIVATE_KEY }}
