name: 🔥 Deploy 🔥
on:
  push:
    branches:
      - main
jobs:
  buildApp:
    name: Build app to server
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies via composer
        uses: fifsky/ssh-action@master
        with:
          command: |
            ${{ secrets.SSH_DEPLOY_COMMANDS }}
          host: ${{ secrets.PRODUCTION_SSH_REMOTE_HOSTNAME }}
          user: ${{ secrets.SSH_DEPLOY_USENAME }}
          key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
          args: '-tt -vvv'
