name: image build and push
on:
  release:
    types: [published]
jobs:
  docker:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          registry: ghcr.io
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/inkomomutane/mimovel:${{ github.ref_name }}, ghcr.io/inkomomutane/mimovel:latest
