name: Push container image to github container registry
on:
  push:
    branches:
      - main
jobs:
  publish_image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: image_build_and_push
        run: |
         docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} ghcr.io
         docker build . --tag ghcr.io/inkomomutane/mimovel:latest   --tag  --tag ghcr.io/inkomomutane/mimovel:{{ github.ref_name }} --platform linux/amd64,linux/arm/v7,linux/arm64/v8
         docker push ghcr.io/inkomomutane/mimovel:latest
         docker push ghcr.io/inkomomutane/mimovel:{{ github.ref_name }}
