name: test
on:
  push:
    branches:
    - main

env:
  FIRST_NAME: Mona
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls -a
            echo "env_var:$FIRST_NAME"
            exit 1
          host: ${{ secrets.SSH_SERVER }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          pass: ${{ secrets.PASS }}
          args: "-tt -vvv"
